django_blog/src/blog/urls.py
from django.contrib import admin
from django.urls import include, path
from blog import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_blog/src/posts/urls.py
from django.urls import path
from posts.views import BlogHome, BlogPostCreate, BlogPostUpdate, BlogPostDetail, BlogPostDelete
from django.contrib.auth.decorators import login_required

app_name = "posts"

urlpatterns = [
    path('', BlogHome.as_view(), name='home'),
    path('create/', login_required(BlogPostCreate.as_view()), name='create'),
    path('<str:slug>/', BlogPostDetail.as_view(), name='post'),
    path('update/<str:slug>/', login_required(BlogPostUpdate.as_view()), name='update'),
    path('delete/<str:slug>/', login_required(BlogPostDelete.as_view()), name='delete'),
]

django_blog/src/posts/models.py
from typing import Type
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.options import Options
from django.template.defaultfilters import slugify
from django.urls import reverse


User = get_user_model()


class BlogPost(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name="Title")
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now_add=True)
    created_on = models.DateField(blank=True, null=True)
    published_on = models.BooleanField(default=False, verbose_name="published")
    content = models.TextField(blank=True, verbose_name="content")
    thumbnail = models.ImageField(blank=True, upload_to= 'blog')


    class Meta:
        ordering = ['-created_on']
        verbose_name = "Blog Post"


    def __str__(self):
        return self.title


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            
        super().save(*args, **kwargs)


    @property
    def author_default(self):
        return self.author.username if self.author else "Unknown author"

    def get_absolute_url(self):
        return reverse('posts:home')

django_blog/src/posts/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from posts.models import BlogPost

class BlogHome(ListView):
    model = BlogPost
    context_object_name = "posts"

    def get_queryset(self):
        querySet = super().get_queryset()
        if self.request.user.is_authenticated:
            return querySet

        return querySet.filter(published_on=True)

class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = "posts/BlogPost_create.html"
    fields = ["title", "content",]

class BlogPostUpdate(UpdateView):
    model = BlogPost
    template_name = "posts/BlogPost_update.html"
    fields = ["title", "content", "published_on"]
    slug_field = "slug"  

class BlogPostDetail(DetailView):
    model = BlogPost
    context_object_name = "post"

class BlogPostDelete(DeleteView):
    model = BlogPost
    context_object_name = "post"
    success_url = reverse_lazy("posts:home")

django_blog/src/posts/templates/posts/BlogPost_create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h1>Create a New Blog Post</h1>
      <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create Post">
      </form>
    </div>
  </div>
</div>
{% endblock %}

django_blog/src/posts/templates/posts/BlogPost_update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h1>Update a New Blog Post</h1>
      <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update Post">
      </form>
    </div>
  </div>
</div>
{% endblock %}

django_blog/src/posts/templates/posts/blogpost_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h1>Delete Blog</h1>
      <form method="POST">
        {% csrf_token %}
        <p> Do you want to delete this blog "{{post.title}}"</p>
        <input type="submit" value="Delete Post">
      </form>
    </div>
  </div>
</div>
{% endblock %}

django_blog/src/posts/templates/posts/blogpost_detail.html
{% extends 'base.html'%}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Welcome Page/title>
</head>

<body>
    <header>
        {% block title%}
        <h1>My Blog</h1>
        {%endblock%}
    </header>
    {% block content %}
    <main>
        <article>
            <h2>{{post.title}}</h2>
            {% if request.user.is_authenticated %}
            {% if post.thumbnail %}
            <!-- <img src="{{post.thumbnail.url}}" alt="Article Image">  only if you and to add an image -->
            {% else %}
            <p>No thumbnail available</p>
            {% endif %}
            {% endif %}
            <p> {{post.content|safe}}.</p>
        </article>
    </main>
    {% endblock %}

    <footer>
        <p>&copy; 2023 My Blog. All rights reserved.</p>
    </footer>
</body>

</html>

django_blog/src/posts/templates/posts/blogpost_list.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Welcome Page</title>
</head>

<body>
    <header>
        {% block title %}
        <h1>My Blog</h1>
        {% endblock %}
    </header>

    <nav>
        <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
        </ul>
    </nav>
    {% block content %}
    <main>
        {% for post in posts %}
        <article>
            <div class="post-title">
                <h2>{{ post.title }}</h2>
                {% if request.user.is_authenticated %}
                <div>
                    {% if post.slug %}
                    <a href="{% url 'posts:update' slug=post.slug %}" style="text-decoration: none; color: #007bff; display: flex; align-items: center;">
                        <svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit" style="width: 18px; height: 18px; margin-right: 10px;">
                            <path d="M10.94 2.63L2 11.58V16h4.42l8.95-8.96L19.37 3.7 10.94 2.63z"></path>
                            <line x1="23" y1="1" x2="1" y2="23"></line>
                        </svg>
                        Update Post
                    </a>
                    {% else %}
                    <p>Empty slug for post: {{ post.title }}</p>
                    {% endif %}
                    {% if post.slug %}
                    <a href="{% url 'posts:delete' slug=post.slug %}" style="text-decoration: none; color: #007bff; display: flex; align-items: center;">
                        <svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash" style="width: 18px; height: 18px; margin-right: 10px;">
                            <polyline points="3 6 5 6 21 6"></polyline>
                            <path d="M5.921 6l-.92-4.545A1.99 1.99 0 0 1 7 0h10c1.053 0 1.938.636 2.321 1.545L18.08 6M6 6v14a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V6"></path>
                        </svg>
                        Delete Post
                    </a>
                    {% else %}
                    <p>Empty slug for post: {{ post.title }}</p>
                    {% endif %}
                </div>
                {% endif %}
            </div>
            <p>Posted on <span class="date">{{ post.created_on|date:'j F y' }}</span> by <span
                    class="author">{{post.author_default }}</span></p>
            <p>{{ post.content|safe|truncatewords:50 }}.</p>

            <form action="{% url 'posts:post' slug=post.slug %}">
                <button> Read article</button>
            </form>
        </article>
        {% endfor %}
    </main>
    {% endblock %}

    <footer>
        <p>&copy; 2023 My Blog. All rights reserved.</p>
    </footer>
</body>

</html>

django_blog/src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8" />
    {% block title%}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-9I5NfC6lgHT6JX54+8FQ0AdmANVojjnc3jimW2odxyEsYkJrVl6bi7hpU9RfX2x4U3f0PTT8D7fruc2RQbgGQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>

<body>
    <nav>
        <ul>
            <li><a href="{% url 'posts:home' %}">Home</a></li>
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'posts:create' %}">Create Article</a></li>
            {% endif %}
        </ul>
    </nav>
    <section id="blog">
        {% block content%}
        {%endblock%}
    </section>
</body>

</html>